routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('verifyemailfirst', 'Auth\RegisterController@verifyEmailFirst')->name('verifyemailfirst');
Route::get('verify/{email}/{verifyEmailToken}', 'Auth\RegisterController@emailSent')->name('sendVerifyEmail');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/userlogout', 'Auth\LoginController@logout')->name('userlogout');
Route::prefix('admin')->group(function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/add-bus', 'Admin\BusController@index')->name('admin.add-bus');
    Route::post('/add-bus-detail', 'BusController@save_bus_data')->name('save-bus-data');
});
Route::get('/route', 'RouteController@index')->name('route');
Route::post('/route', 'RouteController@addRoute')->name('route.add');
Route::post('/routeupdate','RouteController@update')->name('route.update');
Route::get('/add-schedule', 'ScheduleController@index')->name('add-schedule');
Route::post('/add-schedule', 'ScheduleController@addSchedule')->name('schedule.add');
Route::post('/view-schedule', 'ScheduleController@viewSchedule')->name('schedule.view');
Route::post('/deleteschedule', 'ScheduleController@deleteSchedule')->name('schedule.delete');
Route::post('/updateschedule', 'ScheduleController@updateSchedule')->name('schedule.update');
Route::get('/adminseat', 'AdminSeatController@index')->name('adminseat');
Route::post('/adminseatlayout','AdminSeatController@addSeatLayout')->name('add.bus.seat.layout');
Route::get('/seat/{value}', 'ClientSeatController@index')->name('client.seat');
Route::get('/fetchseat/{value}', 'ClientSeatController@fetch')->name('client.seat.book');
Route::post('/search', 'SearchController@searchBus')->name('search.bus');
Route::post('/extendedsearch')->name('extendedSearch');
Route::post('/booking','ClientSeatController@book')->name('booking');
Route::post('/proceedpayment','PaymentController@index')->name('proceedpayment');
Route::post('/confirmpayment','PaymentController@confirmpayment')->name('confirmpayment');
Route::group(['middleware' => ['auth:admin']], function () {
    Route::resource('addbus', 'BusController');
    Route::POST('addbus', 'BusController@addBus');
    Route::POST('editBus', 'BusController@editBus');
    Route::POST('deleteBus', 'BusController@deleteBus');
});

//for development only, dont forget to delete it later
Route::get('/confirmpayment', function () {
    return view('client-seat-view.payment');
});

Route::get('/myreservation','ClientController@index')->name('myreservation');
Route::get('/req/{value}/{user}','ClientController@requestCancellation')->name('cancel-your-reservation');


// Route::get('/{p1?}/{p2?}/{p3?}/{p4?}', function () {
//     return redirect('/');
// });

resources/views/adminlayouts/admin-layouts.blade.php
<!DOCTYPE html>
<html>
<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{asset('semantic/dist/semantic.min.css')}}" rel="stylesheet">
    @yield('css')
    <link href="{{asset('css/style.css')}}" rel="stylesheet">


</head>

<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">LOGO</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav">

                @if(auth::guard('admin')->check())
                    {{--<li><a href="{{route('addbus.index')}}">Add Bus</a></li>--}}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Bus Management <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{route('addbus.index')}}">Add Bus</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{route('route')}}">Route Management</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{route('add-schedule')}}">Schedule Management</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{route('adminseat')}}">Seat Layout</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Manage Reservation</a></li>
                    <li><a href="#">Support</a></li>
                @endif
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if (Auth::guard('admin'))


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('admin.logout') }}"
                                   onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ route('admin.logout') }}" method="POST"
                                      style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->

    <div class="clear-fix"></div>
</nav>

<div class="container">
    @yield('content')

</div>


<script src="{{ asset('js/app.js') }}"></script>
@yield('js')
@yield('moment')
@yield('datetimepickerjs')
{{--  @yield('customjs')--}}
<script src="{{asset('js/customscript.js')}}"></script>
@yield('seat')
@yield('ajax')


</body>
</html>